# Generated by Django 5.2.8 on 2025-11-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'ordering': ['username']},
        ),
    ]
