# Generated by Django 5.2.8 on 2025-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_login_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Accessories', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Laptop', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Mobile', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
