# Generated by Django 5.2.8 on 2025-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_accessories_laptop_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Accessories', max_length=25),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Laptop', max_length=25),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Accessories', 'Accessories')], default='Mobile', max_length=25),
        ),
    ]
