# Generated by Django 5.2.8 on 2025-11-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_accessories_category_alter_laptop_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
