# Generated by Django 5.2.8 on 2025-11-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
